### ISSUE TITLE
Use cors if wordpress is http

### ISSUE THREAD

**Issue by luisherranz** [worona/google-analytics-app-extension-worona#1]
When calling the WP-API from a https connection we have to use cors.

Affected line:
https://github.com/worona/google-analytics-app-extension-worona/blob/d3312d5d3e69a9152a077dfb13e03bd31c6ce76c/src/app/sagas/index.js#L95

The logic to determine if cors should be added at the beginning is something like this:
```javascript
siteUrl.startsWith('http://') && window.location.host === 'https'
```

In that case, the call to the WP-API should include `https://cors.worona.io/`, like this:
`https://cors.worona.io/${siteUrl}/?rest_route=/`

**Comment by luisherranz** [comment]
Thanks @DAreRodz! Could you please deploy it to prod?

**Comment by DAreRodz** [comment]
Yeah, of course!

**Comment by DAreRodz** [comment]
Done!

**Comment by luisherranz** [comment]
Awesome! Thanks!
